<?php
/**
 * Implements hook_preprocess_html() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function gatewayd8_preprocess_html(&$variables) {
  // Add information about the number of sidebars.
  if (!empty($variables['page']['aside_content'])) {
    $variables['attributes']['class'][] = 'layout-one-sidebar';
  }
  else {
    $variables['attributes']['class'][] = 'layout-no-sidebars';
  }

}